package thirikkale.util.db;

public class SQLStatements {
	public static final String CREATE_PARTNER = "INSERT INTO PARTNER(NAME, EMAIL, PASSWORD, PHONENO1, PHONENO2, PHONENO3, CREATEDDATETIME) VALUES (?,?,?,?,?,?,NOW())";

	public static final String SELECT_PARTNER = "SELECT ID FROM PARTNER WHERE EMAIL=?";

	public static final String CREATE_VEHICLE = "INSERT INTO VEHICLE(PARTNER_ID, MAKE_ID, MAKE_NAME, MODEL_ID, MODEL_NAME, NOOF_PASSENGERS, NOOF_LUGGAGES, NOOF_DOORS, TRANSMITTION_TYPE, AC, FUEL_TYPE, ENGINE_CAPACITY, ALLOW_SELF_DRIVE, REFUNDABLE_DEPOSIT, RENTAL_PER_DAY, FREE_MILAGE, CHARGE_PER_KM, IMG_COUNT, IMG_MAP) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())";
}
